// Fake users
const users = [
  { id: 1, name: "Maya", age: 20, emoji: "M", color: "#167a5f", bio: "Exploring Austin one ramen spot at a time", tags: ["Food & Drink", "Arts"], vibe: "Spontaneous, intro-leaning" },
  { id: 2, name: "Jordan", age: 24, emoji: "J", color: "#2e7d9b", bio: "New to Austin, looking for real plans", tags: ["Outdoors", "Social"], vibe: "Outgoing, planner" },
  { id: 3, name: "Priya", age: 21, emoji: "P", color: "#7b5ea7", bio: "UT junior, obsessed with trying new things", tags: ["Food & Drink", "Learning"], vibe: "Spontaneous, extro-leaning" },
  { id: 4, name: "Eli", age: 22, emoji: "E", color: "#c0832a", bio: "Photography + food = my whole personality", tags: ["Arts", "Food & Drink"], vibe: "Intro-leaning, spontaneous" },
  { id: 5, name: "Sofia", age: 23, emoji: "S", color: "#b5474a", bio: "Recent grad, rebuilding my social life", tags: ["Social", "Outdoors"], vibe: "Outgoing, spontaneous" },
];

// Fake experiences
const experiences = [
  {
    id: 1,
    emoji: "🍜",
    title: "Late-night ramen tasting on 6th",
    category: "Food & Drink",
    date: "This Friday, 8pm",
    location: "East 6th Street",
    price: "Free",
    groupSize: "4–6",
    spots: 2,
    compat: "Strong match",
    members: [1, 3, 4],
    description: "Found a spot doing a soft launch — they want a small group to try the menu. No cost, just good food and honest feedback.",
    host: 1,
  },
  {
    id: 2,
    emoji: "🧱",
    title: "Pottery drop-in at Radius Studio",
    category: "Arts & Culture",
    date: "Saturday, 11am",
    location: "South Congress",
    price: "$35",
    groupSize: "4–6",
    spots: 3,
    compat: "Good match",
    members: [2, 5],
    description: "Two-hour wheel throwing session at Radius. No experience needed. They'll walk you through everything.",
    host: 5,
  },
  {
    id: 3,
    emoji: "🌅",
    title: "Sunrise hike at Barton Creek + breakfast",
    category: "Outdoors",
    date: "Sunday, 6:30am",
    location: "Barton Creek Greenbelt",
    price: "$15",
    groupSize: "6–10",
    spots: 4,
    compat: "Great match",
    members: [2, 3, 5, 4],
    description: "Tether-hosted outing. 90-min trail, then breakfast tacos at a spot nearby. Moderate fitness level.",
    host: null,
    tether: true,
  },
  {
    id: 4,
    emoji: "🎬",
    title: "Rooftop film screening — Amelie",
    category: "Arts & Culture",
    date: "Next Thursday, 7pm",
    location: "The Arrive Hotel rooftop",
    price: "$18",
    groupSize: "4–6",
    spots: 2,
    compat: "Good match",
    members: [1, 4],
    description: "Outdoor screening with blankets and snacks provided. Arrive early to meet your group before it starts.",
    host: null,
    tether: true,
  },
];
